// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: internal/grpc/pb/webrtc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebRTCService_JoinRoom_FullMethodName = "/webrtc.WebRTCService/JoinRoom"
)

// WebRTCServiceClient is the client API for WebRTCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebRTCServiceClient interface {
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
}

type webRTCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebRTCServiceClient(cc grpc.ClientConnInterface) WebRTCServiceClient {
	return &webRTCServiceClient{cc}
}

func (c *webRTCServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, WebRTCService_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebRTCServiceServer is the server API for WebRTCService service.
// All implementations must embed UnimplementedWebRTCServiceServer
// for forward compatibility.
type WebRTCServiceServer interface {
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	mustEmbedUnimplementedWebRTCServiceServer()
}

// UnimplementedWebRTCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebRTCServiceServer struct{}

func (UnimplementedWebRTCServiceServer) JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedWebRTCServiceServer) mustEmbedUnimplementedWebRTCServiceServer() {}
func (UnimplementedWebRTCServiceServer) testEmbeddedByValue()                       {}

// UnsafeWebRTCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebRTCServiceServer will
// result in compilation errors.
type UnsafeWebRTCServiceServer interface {
	mustEmbedUnimplementedWebRTCServiceServer()
}

func RegisterWebRTCServiceServer(s grpc.ServiceRegistrar, srv WebRTCServiceServer) {
	// If the following call pancis, it indicates UnimplementedWebRTCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebRTCService_ServiceDesc, srv)
}

func _WebRTCService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebRTCServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebRTCService_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebRTCServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebRTCService_ServiceDesc is the grpc.ServiceDesc for WebRTCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebRTCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webrtc.WebRTCService",
	HandlerType: (*WebRTCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinRoom",
			Handler:    _WebRTCService_JoinRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/pb/webrtc.proto",
}
